### ISSUE TITLE
Expand all feature

### ISSUE THREAD

**Issue by hmaclean82** [stven0king/JsonHandleView#1]
It would be great to have the ability to expand / collapse all 
thanks
Hamish

**Comment by stven0king** [comment]
@hmaclean82 Thanks for your advice.
I have added this feature.
You can see the 1.2.1 version.

**Comment by hmaclean82** [comment]
great thanks, although i'm getting this crash, I think it may be unrelated to your change, it is just noticeable now that all the objects are expanded:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.json.JSONArray.length()' on a null object reference
        at com.dandan.jsonhandleview.library.JsonViewLayout$JsonViewOnClickListener.onClick(JsonViewLayout.java:210)
        at android.view.View.callOnClick(View.java:6621)
        at com.dandan.jsonhandleview.library.JsonView.collapse(JsonView.java:118)
        at com.dandan.jsonhandleview.library.JsonViewLayout.operationJsonView(JsonViewLayout.java:391)
        at com.dandan.jsonhandleview.library.JsonViewLayout.clickAllView(JsonViewLayout.java:372)
        at com.dandan.jsonhandleview.library.JsonViewLayout.clickAllView(JsonViewLayout.java:381)
        at com.dandan.jsonhandleview.library.JsonViewLayout.clickAllView(JsonViewLayout.java:381)
        at com.dandan.jsonhandleview.library.JsonViewLayout.expandAll(JsonViewLayout.java:359)`

Here I think you also want to protect against null in your if statement (the JSONObject.names() can return null)

` JSONArray array = isJsonArray ? (JSONArray) value : ((JSONObject) value).names();
                if (!isJsonArray && array.length() == 1 && "nameValuePairs".equals(array.opt(0).toString())) {`

**Comment by stven0king** [comment]
Yes, what you said is correct. 
Maybe I didn't consider all the data. 
Some unusual data may cause a crash.
